### ISSUE TITLE
Allow linewise ranges

### ISSUE THREAD

**Issue by jez** [owickstrom/pandoc-emphasize-code#2]
First just let me say that I'm a big fan of this filter; thanks!

I'd like to achieve an affect similar to this example in [the React docs][1]:

<img width="640" alt="screen shot 2018-06-08 at 12 11 03 am" src="https://user-images.githubusercontent.com/5544532/41144078-79867e72-6ab0-11e8-94f9-818efe2dd58b.png">

In particular, I'd like to be able to specify that entire lines should be highlighted, from the far left of the `<pre>` tag to the far right. With a bit of tinkering, I managed to get this working in the Chrome inspector almost entirely with CSS:

<img width="722" alt="screen shot 2018-06-08 at 12 05 13 am" src="https://user-images.githubusercontent.com/5544532/41144136-b580d2b0-6ab0-11e8-9c19-f11f11d99267.png">

The one trick is that I had to add a CSS class to the generated `<mark>` tags to indicate whether it should mark within the line (`.inline`) or the entire line (`.block`):

~~~html
<pre><code>```{.haskell <mark class="inline">emphasize=2:3-2:14,3:3-3:12</mark>}
myFunc = do
<mark class="block">  newStuffHere</mark>
  andThisToo notThis
  notSoRelevant
```</code></pre>
~~~

I'm considering patching the `pandoc-emphasize-code` grammar to accept ranges like this:

```sml
line number     = natural number;
column number   = natural number;
position        = line number, ":", column number;
range           = position, "-", position
                | line number, "-", line number;           (* new *)
ranges          = range, { (",", range) };
```

This would allow enough information to be tracked to determine whether we should put the `.inline` class or the `.block` class on the generated tag. It's also slightly friendlier; in case the code changes within a line, you don't need to update the column positions to ensure that all the characters on that line remain highlighted.

Curious to hear your thoughts on whether this would be a welcome change, and whether you have preferences for how it should be implemented.

Thanks again for this filter!

- - -

P.S. This was the bit of CSS needed to get it to work:

```css
pre code {
  position: relative;
  min-width: 100%;
  z-index: 1;
}

mark.block::after {
    content: "";
    position: absolute;
    background-color: yellow;
    left: -16px;
    right: -16px;
    height: 19px;
    margin-top: 2px;
    z-index: -1;
}
```

[1]: https://reactjs.org/tutorial/tutorial.html#passing-data-through-props
